### ISSUE TITLE
Extra changes for github pages?

### ISSUE THREAD

**Issue by mwweinberg** [yining1023/styleTransfer_spell#1]
First, thank you so much for the demo. I was excited to try it out and doubly excited when I got it to actually work.

Unfortunately, I am running into problems now that I am trying to share my success with someone else.  Everything works on local.  I tried to upload my version to github pages (https://michaelweinberg.org/mcDemo/), but got a number of errors (they all appear to be a riff on "Uncaught Error: Not found variable Variable_35/Adam at XMLHttpRequest.r.onload (checkpointLoader.js:69)".  In an attempt to troubleshoot I uploaded a clone of this version to my repo. It worked fine until I changed the model from your model to my model (https://michaelweinberg.org/stspell/).  At that point I go the same errors.

Is there some sort of additional formatting that I need to do when adding the model to github pages?  Or is there something else that I'm missing?

thanks again!

**Comment by yining1023** [comment]
Hi @mwweinberg Thank you for trying the demo!

There is no additional formatting for hosting on GitHub pages. But it is weird that it works locally but not on GitHub pages. May I see your model folder? Does it only have one `manifest.json` file, One `Variable` file, and `Variable_1` to `Variable_47`? Or it also has things like `Variable_8_Adam`. If it has  like `Variable_8_Adam`, maybe the last script in the last step([4. Converting model to ml5js](https://github.com/yining1023/styleTransfer_spell#4-converting-model-to-ml5js)) is not sucessfully excuted:
```
python scripts/remove_optimizer_variables.py --output_dir=src/ckpts/YOUR_FOLDER_NAME
```
After running ths above script again(under the `fast-style-transfer-deeplearnjs` directory), we need to make sure that you only have 49 files inside of the model folder. Let me know if this works.

Looking forward to seeing your new model!

**Comment by mwweinberg** [comment]
That was it!  I had a bunch of _Adam files. I must have skipped that last script.  Thank you so much.  The working model is here:

https://michaelweinberg.org/climberdemo/

I'm planning on doing a bunch of other things with it but wanted to make sure that this part was working first.  Thank you again!
